project_id = "csixccpoxpnwowbgkoyw"

[functions]
[functions.make-outbound-call]
verify_jwt = true

[functions.call-webhook]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.process-openai]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true